name: Demo
on: workflow_dispatch
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello_step
        run: echo "Welcome to Github"
 Test:
   runs-on: ubuntu-latest
   steps:
     - name: Test_phase
       run: echo "Running test cases"
Deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Deploy_the_app
       run: echo "Deploying the app"
  
