name: Demo

on:
  push:
    branches: 
      - main
      - develop
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{vars.MY_NAME}}"

  
